"""
UART and TLV constants for IWR6843AOP radar viewer.
"""

# ============================================================
# UART / TLV CONSTANTS
# ============================================================

MAGIC_WORD = b"\x02\x01\x04\x03\x06\x05\x08\x07"

MAX_PACKET_LENGTH = 300000

# Out-of-Box SDK TLV types
OOB_TLV_DETECTED_POINTS = 1
OOB_TLV_RANGE_PROFILE = 2
OOB_TLV_NOISE_PROFILE = 3
OOB_TLV_AZIMUT_STATIC_HEAT_MAP = 4
OOB_TLV_RANGE_DOPPLER_HEAT_MAP = 5
OOB_TLV_STATS = 6
OOB_TLV_SIDE_INFO = 7

# 3D People Tracking / People Counting common TLV types
PT_TLV_POINT_CLOUD_SMALL = 6
PT_TLV_TARGET_LIST_SMALL = 7
PT_TLV_TARGET_INDEX_SMALL = 8
PT_TLV_TARGET_HEIGHT_SMALL = 9
PT_TLV_PRESENCE_SMALL = 11

# Extended TLV IDs used by many 3D People Counting firmware builds
PT_TLV_TARGET_LIST_EXT = 1010
PT_TLV_TARGET_INDEX_EXT = 1011
PT_TLV_TARGET_HEIGHT_EXT = 1012
PT_TLV_COMPRESSED_POINT_CLOUD_EXT = 1020
PT_TLV_PRESENCE_EXT = 1021

PEOPLE_TRACKING_POINT_CLOUD_TLVS = {
    PT_TLV_POINT_CLOUD_SMALL,
    PT_TLV_COMPRESSED_POINT_CLOUD_EXT
}

PEOPLE_TRACKING_TARGET_LIST_TLVS = {
    PT_TLV_TARGET_LIST_SMALL,
    PT_TLV_TARGET_LIST_EXT
}

PEOPLE_TRACKING_TARGET_INDEX_TLVS = {
    PT_TLV_TARGET_INDEX_SMALL,
    PT_TLV_TARGET_INDEX_EXT
}

PEOPLE_TRACKING_TARGET_HEIGHT_TLVS = {
    PT_TLV_TARGET_HEIGHT_SMALL,
    PT_TLV_TARGET_HEIGHT_EXT
}

PEOPLE_TRACKING_PRESENCE_TLVS = {
    PT_TLV_PRESENCE_SMALL,
    PT_TLV_PRESENCE_EXT
}

KNOWN_PEOPLE_TLVS = (
    PEOPLE_TRACKING_POINT_CLOUD_TLVS |
    PEOPLE_TRACKING_TARGET_LIST_TLVS |
    PEOPLE_TRACKING_TARGET_INDEX_TLVS |
    PEOPLE_TRACKING_TARGET_HEIGHT_TLVS |
    PEOPLE_TRACKING_PRESENCE_TLVS
)

KNOWN_OOB_TLVS = {
    OOB_TLV_DETECTED_POINTS,
    OOB_TLV_RANGE_PROFILE,
    OOB_TLV_NOISE_PROFILE,
    OOB_TLV_AZIMUT_STATIC_HEAT_MAP,
    OOB_TLV_RANGE_DOPPLER_HEAT_MAP,
    OOB_TLV_STATS,
    OOB_TLV_SIDE_INFO
}
